### ISSUE TITLE
どのファイルを開いてもエラーが表示される。

### ISSUE THREAD

**Issue by fuminori-hakoishi** [ics-creative/project-japanese-proofreading#25]
```
The Language Server Textlint server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

と右下に表示され、

出力から`Language Server Textlint`を見ると

```
Error: Not found available plugin for .swiftinterface
    at TextlintKernel.<anonymous> (/Users/<ユーザ名>/.vscode/extensions/ics.japanese-proofreading-1.1.0/node_modules/@textlint/kernel/lib/src/textlint-kernel.js:152:23)
    at Generator.next (<anonymous>)
    at /Users/<ユーザ名>/.vscode/extensions/ics.japanese-proofreading-1.1.0/node_modules/@textlint/kernel/lib/src/textlint-kernel.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/<ユーザ名>/.vscode/extensions/ics.japanese-proofreading-1.1.0/node_modules/@textlint/kernel/lib/src/textlint-kernel.js:23:12)
    at TextlintKernel._parallelProcess (/Users/<ユーザ名>/.vscode/extensions/ics.japanese-proofreading-1.1.0/node_modules/@textlint/kernel/lib/src/textlint-kernel.js:147:16)
    at /Users/<ユーザ/.vscode/extensions/ics.japanese-proofreading-1.1.0/node_modules/@textlint/kernel/lib/src/textlint-kernel.js:110:25
    at async validateTextDocument (/Users/<ユーザ名/.vscode/extensions/ics.japanese-proofreading-1.1.0/out/server.js:90:21)
[Error - 12:04:29 PM] Connection to server got closed. Server will not be restarted.
```

と表示されます。

今回はたまたま.swiftinterfaceファイルを開いたが、その他の適当なファイルでも同じようにエラーが発生します。

また、本エラーログは、Macbook Air M2 macOS 13.0.1だが、Windows10機でも同様のエラーが発生しています。

ご報告まで。

**Comment by ics-furudate** [comment]
ご報告ありがとうございます。

#26 と関連して、特定の拡張子を持つファイルを開くとプラグインがクラッシュする問題がありました。
v1.2.0（2023年2月8日リリース）にて修正を行い、この問題を改善できたと思いますので、Issueはクローズとさせてください。

▼ v1.2.0で.swiftinterfaceファイルを開いても、`Language Server Textlint`の出力（エラー）が表示されずクラッシュしない

![スクリーンショット 2023-02-08 15 56 02](https://user-images.githubusercontent.com/78718425/217457467-9305370e-50a3-44dd-8717-3a77f5c2dd53.png)

プラグインをアップデートしても改善されていない場合は、恐れ入りますが改めてご報告いただけると幸いです。
