### ISSUE TITLE
拡張子がないファイルでクラッシュする

### ISSUE THREAD

**Issue by rmuraix** [ics-creative/project-japanese-proofreading#26]
## 概要
拡張子がないテキストファイルを開くとテキスト校正くんがクラッシュする。  

<img alt="スクリーンショット_20221126_150517" src="https://user-images.githubusercontent.com/35632215/204075073-00120407-8f4e-45cb-a4ca-be72d6ea8eff.png">

## バージョン
テキスト校正くん　v1.1.0  
Visual Studio Code v1.73.1
## 期待される動作
拡張子がないファイルに対しては文章チェックを行わない。
## エラーログ
`LICENSE`というファイルを開いたときのもの。パス中のユーザ名は`<user>`に置き換えてある。  

```
c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224
            throw new Error("should specify the extension.\nex) .md");
                  ^

Error: should specify the extension.
ex) .md
    at TextLintEngine.executeOnText (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224:19)
    at validateTextDocument (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\out\server.js:90:34)
[Info  - 15:04:40] Connection to server got closed. Server will restart.
c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224
            throw new Error("should specify the extension.\nex) .md");
                  ^

Error: should specify the extension.
ex) .md
    at TextLintEngine.executeOnText (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224:19)
    at validateTextDocument (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\out\server.js:90:34)
[Info  - 15:04:41] Connection to server got closed. Server will restart.
c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224
            throw new Error("should specify the extension.\nex) .md");
                  ^

Error: should specify the extension.
ex) .md
    at TextLintEngine.executeOnText (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224:19)
    at validateTextDocument (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\out\server.js:90:34)
[Info  - 15:04:42] Connection to server got closed. Server will restart.
c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224
            throw new Error("should specify the extension.\nex) .md");
                  ^

Error: should specify the extension.
ex) .md
    at TextLintEngine.executeOnText (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224:19)
    at validateTextDocument (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\out\server.js:90:34)
[Info  - 15:04:43] Connection to server got closed. Server will restart.
c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224
            throw new Error("should specify the extension.\nex) .md");
                  ^

Error: should specify the extension.
ex) .md
    at TextLintEngine.executeOnText (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\node_modules\textlint\lib\src\engine\textlint-engine-core.js:224:19)
    at validateTextDocument (c:\Users\<user>\.vscode\extensions\ics.japanese-proofreading-1.1.0\out\server.js:90:34)
[Error - 15:04:44] Connection to server got closed. Server will not be restarted.

```

**Comment by ics-furudate** [comment]
ご報告いただきありがとうございます。
また、返答を長らくお待たせしており失礼しました。

現象を確認し、拡張子がないファイルでは文章校正を行わずクラッシュしないよう修正しました。

こちらで、報告いただいた不具合は改善できたと思いますので、Issueはクローズとさせてください。
